### ISSUE TITLE
Parallelize ansible playbook

### ISSUE THREAD

**Issue by brusMX** [zikalino/openshift-work#7]
Break the playbook into pieces and make sure that they have no dependencies to minimize deploying time.

**Comment by brusMX** [comment]
WIP  commit id 7f20bcb8e52d5beb1889991d88fb5b5cf35a613f

**Comment by brusMX** [comment]
This is pretty much done, the only problem now is to verify that everything was provisioned @zikalino will help out

**Comment by zikalino** [comment]
@brusMX i have added tasks to wait for resources to be provisioned (vms and public ip addresses), but i am still concerned that there's no information displayed when something goes wrong. i have created a new issue #20 for this. so i will close this one
